[build]
builder = "nixpacks"
buildCommand = "cd server && bun install"

[deploy]
startCommand = "cd server && bun run start"
healthcheckPath = "/health"
healthcheckTimeout = 100

[nixpacks]
bun-version = "latest"
