[build]
builder = "nixpacks"
buildCommand = "cd server && bun install"

[deploy]
startCommand = "cd server && bun start"
healthcheckPath = "/"
healthcheckTimeout = 100

[nixpacks]
bun-version = "latest"
